spring:
  application:
    name: image-animation-videos
  ai:
    openai:
      base-url: http://localhost:8070
      api-key: sk-local
server:
  port: 9080
#video:
#  input:
#    path: /data/images/
#  output:
#    path: /data/output/
#  duration: 8


